sentry:
    register_error_listener: false
    messenger:
        enabled: true
        capture_soft_fails: false
    options:
        default_integrations: true
        send_attempts: 3
        attach_stacktrace: true
        send_default_pii: true
        integrations:
            - Sentry\Integration\IgnoreErrorsIntegration
