services:
    _defaults:
        autowire: true
        autoconfigure: true

    Lingoda\SentryBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $bubble: false

    Lingoda\SentryBundle\Sentry\RepresentationSerializer:
        arguments:
            $options: '@sentry.client.options'

    Lingoda\SentryBundle\Sentry\Serializer\NamespaceJsonSerializer: ~

    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }
