name: ci
on:
  pull_request: ~
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3', '8.4']
        symfony: ['6.4', '7.3', '8.0']
      fail-fast: false
    steps:
      -   name: cancel
          uses: styfle/cancel-workflow-action@0.12.1

      -   name: checkout
          if: ${{ !cancelled() }}
          uses: actions/checkout@v4

      -   name: Setup PHP
          if: ${{ !cancelled() }}
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php }}

      -   name: Composer update on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
          if: ${{ !cancelled() }}
          run: |
            composer require --no-update symfony/flex
            composer config --no-plugins allow-plugins.symfony/flex true
            SYMFONY_REQUIRE=${{ matrix.symfony }} composer install --classmap-authoritative --prefer-dist

      -   name: Lint
          if: ${{ !cancelled() }}
          run: composer validate

      -   name: phpspec
          if: ${{ !cancelled() }}
          run: vendor/bin/phpspec run --no-code-generation

      -   name: Static analysis on src with PHPStan
          if: ${{ !cancelled() }}
          run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G --no-progress --no-interaction

      -   name: Static analysis on tests with PHPStan
          if: ${{ !cancelled() }}
          run: vendor/bin/phpstan analyse -c phpstan.test.neon --memory-limit=1G --no-progress --no-interaction

      -   name: Run unit tests
          if: ${{ !cancelled() }}
          run: vendor/bin/phpunit
